import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuSide from "./components/MenuSide";
import SideBarComponent from "./components/SideBarComponent";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" min-h-screen font-[family-name:var(--font-geist-sans)] flex">
          <SidebarProvider>
          <div className="fixed top-0 left-0 h-screen bg-white border-r shadow-md">
              <MenuSide />
              
            </div>
            <SideBarComponent />
            <div className="ml-[60px] flex-1 h-screen overflow-y-auto px-0 md:px-6">
              <SidebarTrigger className="ml-[3px]"/>
              {children}
            </div>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
